### ISSUE TITLE
macos 找不到设备

### ISSUE THREAD

**Issue by zhengjianyang** [RT-Thread-packages/micropython#187]
<img width="697" alt="图片" src="https://user-images.githubusercontent.com/71212291/179351579-7720557f-9088-489c-aee0-06ab81311e79.png">

设备是存在的、为什么还提示找不到设备

**Comment by zhengjianyang** [comment]
<img width="217" alt="图片" src="https://user-images.githubusercontent.com/71212291/179352039-0751e57d-c038-4d3a-996b-34d18f15535a.png">

**Comment by katsu119** [comment]
我也遇到了一样的问题，我的是big sur

**Comment by AnthonyZhai** [comment]
一样的问题

**Comment by TripleView** [comment]
确实，mac下找不到设备，13的系统

**Comment by cuiyimeng** [comment]
一样的，无法找到设备

**Comment by Yutao-Jin** [comment]
有找到解决方案吗

**Comment by Yutao-Jin** [comment]
使用1.0.8版本可以顺利连接

**Comment by shawn1905** [comment]
同样的问题，系统是13.4，用thonny是可以的

**Comment by Yutao-Jin** [comment]
用1.0.8可以顺利连接

**Comment by shawn1905** [comment]
确实，1.0.8就可以了，中间的版本也不行，另外还有一个问题就是连接后DEVICE FILE LIST那个地方看不到文件，测试了把文件直接传到单板是正常的，就是显示不出来
![截屏2023-07-05 08 28 56](https://github.com/RT-Thread-packages/micropython/assets/22901591/0521ffaa-d8a1-4778-aa12-ec27610cf931)
